=== Harold-Warnes/LMSGI_RA4_DTD/agenda.dtd
<!ELEMENT agenda (contacte*)>
<!ELEMENT contacte (nom, cognom+, tlf, email?, adreca)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT adreca (carrer, num, cp)>
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

=== Harold-Warnes/LMSGI_RA4_DTD/prova.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacte>
        <nom>????</nom>
        <cognom>多多多多</cognom>
        <tlf>123456789</tlf>
        <email>prueba@gmail.com</email>
        <adreca>
            <carrer>av. catalunya</carrer>
            <num>12</num>
            <cp>08080</cp>        
        </adreca>
    </contacte>
</agenda>
